#!/usr/bin/env python3
import tkinter as tk
from PIL import Image, ImageTk
import time
import os
import ast
import socket,threading,sys
#other stuff
f = open("/Users/mimmo/ssh_login_system/login_info.txt", "r")
contents = f.read()
f.close()
users = ast.literal_eval(contents)
#variables
stuff = ""
newlist = []
login = ""
inp = ("| => ")

rw = tk.Tk()
rw.title("Login")
rw.configure(bg="grey14")
rw.geometry("500x200")

def echo_data(sock):
   while True:
      try:
         msg = sock.recv(1024).decode('utf8')
         msg_list.insert(tk.END, msg)
      except OSError:
         break

def send(event=None):
   msg = my_msg.get() 
   my_msg.set("")
   s.send(bytes(msg, "utf8"))
   if msg == "{quit}":
      s.close()
      top.quit()

def on_closing(event=None):
    my_msg.set("{quit}")
    send()

def chatroom(host):
	hot = host
	port = 4000
	global s
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	address = (hot,port)
	global top
	top = tk.Tk()
	top.title("Chat Room")
	top.configure(bg="grey14")

	messages_frame = tk.Frame(top)
	global my_msg
	my_msg = tk.StringVar()
	scrollbar = tk.Scrollbar(messages_frame)  
	global msg_list
	msg_list = tk.Listbox(messages_frame, height=15, width=100, yscrollcommand=scrollbar.set, bg="grey14", fg="white")
	scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
	msg_list.pack(side=tk.LEFT, fill=tk.BOTH)
	msg_list.pack()
	messages_frame.pack()

	entry_field = tk.Entry(top, textvariable=my_msg, width="100")
	entry_field.bind("<Return>", send)
	entry_field.pack()

	top.protocol("WM_DELETE_WINDOW", on_closing)

	address = (host,port)
	s.connect(address)

	threading.Thread(target=echo_data, args = (s,)).start()

	tk.mainloop()

def login(self):
	username = e1.get()
	password = e2.get()
	servername = e3.get()
	if username in users:
		if password == users[username]:
			rw.destroy()
			print ("\nlogin successful!\n")
			chatroom(servername)
			
a = tk.Label(rw, text="Username:", fg='white', bg='grey14').grid(row=0)
b = tk.Label(rw, text="Password:", fg='white', bg='grey14').grid(row=1)
c = tk.Label(rw, text="Server IP:", fg='white', bg='grey14').grid(row=2)

e1 = tk.Entry(rw)
e2 = tk.Entry(rw, show="*")
e3 = tk.Entry(rw)
e3.insert(0, 'ex: 127.0.0.0')
e3.bind("<Return>", login)

e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)

rw.mainloop()